{
 "title": "Amazon RDS",
 "description": "Visualize Amazon RDS metrics",
 "tags": [
  "Amazon",
  "AWS",
  "CloudWatch",
  "RDS"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Data Source", "query": "cloudwatch" },
   {
    "name": "account",
    "label": "Account (Fixed)",
    "query": {}
   },
   {
    "name": "region",
    "label": "Region",
    "query": {}
   },
   { "name": "period", "label": "Period [sec]", "query": "60,300,3600" }
  ]
 },
 "panels": [
  { "title": "Instance metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU utilization per instance [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Database connections [count sum]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Available storage space [bytes]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Available RAM [bytes]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read throughput [bytes/sec]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Write throughput [bytes/sec]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read latency [sec]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Write latency [sec]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Read operations [IOPS]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Write operations [IOPS]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}