{
 "title": "The Four Golden Signals",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Data Source", "query": "cloudwatch" },
   {
    "name": "account",
    "label": "Account",
    "query": {}
   },
   {
    "name": "region",
    "label": "Region",
    "query": {}
   },
   {
    "name": "loadbalancer",
    "label": "Loadbalancer",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Latency", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 } },
  { "title": "Traffic", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "Response Time ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "*" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "*" },
     "metricName": "RequestCountPerTarget",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "SampleCount"
    }
   ]
  },
  { "title": "Errors", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Errors 5XX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "HTTPCode_ELB_504_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "SampleCount"
    },
    {
     "accountId": "$account",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "HTTPCode_ELB_500_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "accountId": "$account",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "HTTPCode_ELB_502_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "accountId": "$account",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "HTTPCode_ELB_503_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Errors 4XX ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "HTTPCode_ELB_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Errors 5XX - Target Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "*" },
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Errors 4XX - Target Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "*" },
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  { "title": " Saturation", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Active Connections ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "ActiveConnectionCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Processed Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "ProcessedBytes",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  }
 ]
}