{
 "title": "ECS Fargate",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "cloudwatch" },
   {
    "name": "account",
    "label": "Account",
    "query": {}
   },
   {
    "name": "cluster",
    "label": "Cluster ",
    "query": {}
   },
   {
    "name": "servicename",
    "label": "Service",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "CPUUtilization (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$servicename" },
     "metricName": "CpuUtilized",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "accountId": "$account",
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$servicename" },
     "metricName": "CpuReserved",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Memory Utilization (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$servicename" },
     "expression": "(MemoryUtilized * 100) / MemoryReserved\r\n",
     "metricName": "MemoryUtilized",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "accountId": "$account",
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$servicename" },
     "metricName": "MemoryReserved",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Temporary storage usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$servicename" },
     "metricName": "EphemeralStorageUtilized",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "accountId": "$account",
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$servicename" },
     "metricName": "EphemeralStorageReserved",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Running Task ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$servicename" },
     "metricName": "RunningTaskCount",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Desired Task",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$servicename" },
     "metricName": "DesiredTaskCount",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Pending Task",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$servicename" },
     "metricName": "PendingTaskCount",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Network Reception (bytes/seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$servicename" },
     "metricName": "NetworkRxBytes",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Network Transmission (bytes/seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$servicename" },
     "metricName": "NetworkTxBytes",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Storage Read (bytes/seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$servicename" },
     "metricName": "StorageReadBytes",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Storage Write (bytes/seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$servicename" },
     "metricName": "StorageWriteBytes",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}